name: Half-year calendar

on:
 schedule:
    - cron: '0 0 * * *' # Exécute le workflow tous les jours à minuit

jobs:
 generate-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.YOUR_TOKEN }}
          base: ""
          plugin_isocalendar: yes
